'''
Given two nodes A and B, this protocol creates an entangled pair between them using a heralded connection and a magic distributor. The entanglement is generated by
sending photons from both centers to a middle station, where a double-click event indicates succesful entanglement. The entangled qubits are que electronic spins.
It then measures the resulting state and prints the results, including the Bell state, the time taken for entanglement, and the number of attempts needed.
'''

import netsquid as ns
from netsquid.protocols import Protocol, Signals
from netsquid.nodes import Node
from netsquid.components import INSTR_X, INSTR_Z
import numpy as np
from netsquid_physlayer.heralded_connection import MiddleHeraldedConnection
from nv_2026 import NVParameterSet2026COMPUTAEX 
from netsquid_nv.magic_distributor import NVDoubleClickMagicDistributor
import netsquid.qubits.qubitapi as qapi
from nv_2026 import NVParameterSet2026COMPUTAEX
from snv_2026 import SnVParameterSet2026COMPUTAEX

class Entangler(Protocol):
    def __init__(self, A, B, params, ideal=False):
        if not isinstance(A,Node) or not isinstance(B,Node):
            raise TypeError('A and B must be instances of Node')
        super().__init__(name=f"Entangler_{A.name}_{B.name}")
        self.A = A
        self.B = B
        self.params = params
        self.ideal = ideal

        self.delivery = None
        self.md = None

        self.add_signal('Delivered')
        self.add_signal("Pair ready")

    def _on_delivery(self, event):
        self.send_signal(signal_label="Delivered", result=event)

    def run(self):
        print(f'[{ns.sim_time():.1f} ns ] Beginning entanglement...')

        if not self.ideal:
            p = self.params.to_dict()
        else:
            p = self.params.to_perfect_dict()

        product = p["product_tau_decay_delta_w"]

        conexion = MiddleHeraldedConnection(
            name="Conexion",
            length=1,
            p_loss_length=p["p_loss_lengths_with_conversion"],
            speed_of_light=p["c"],
            dark_count_probability=p["prob_dark_count"],
            detector_efficiency=p["total_detection_eff"],
            visibility=p["visibility"]
        )

        self.md = NVDoubleClickMagicDistributor(
            nodes=[self.A, self.B],
            heralded_connection=conexion,
            length_A=0.5,
            length_B=0.5,
            speed_of_light_A=p["c"],
            speed_of_light_B=p["c"],
            emission_duration_A=p["photon_emission_delay"],
            emission_duration_B=p["photon_emission_delay"],
            emission_fidelity_A=p["emission_fidelity"],
            emission_fidelity_B=p["emission_fidelity"],
            p_loss_length_A=p["p_loss_lengths_with_conversion"],
            p_loss_length_B=p["p_loss_lengths_with_conversion"],
            detector_efficiency=p["total_detection_eff"],
            dark_count_probability=p["prob_dark_count"],
            visibility=p["visibility"],
            tau_decay=self.params.tau_decay,
            delta_w=product/self.params.tau_decay if self.params.tau_decay > 0 else 0.0
        )

        self.md.add_callback(self._on_delivery)
                        
        delivery_finished = self.await_signal(
            sender=self,
            signal_label="Delivered"
        )

        requested_event = self.md.add_delivery(
            memory_positions={
                self.A.ID: 0,
                self.B.ID: 0
            },
            coin_prob_ph_ph=1.0,
            coin_prob_ph_dc=1.0,
            coin_prob_dc_dc=1.0
        )

        yield delivery_finished

        delivered_event = self.get_signal_result(
            "Delivered",
            receiver=self
        )

        self.delivery = None

        if delivered_event is not None:
            self.delivery = self.md.peek_delivery(
                delivered_event,
                allow_archive=True
            )

        if self.delivery is None and requested_event is not None:
            self.delivery = self.md.peek_delivery(
                requested_event,
                allow_archive=True
            )

        if self.delivery is None or self.delivery.sample is None:
            raise RuntimeError(
                "Se recibió la señal Delivered, pero MagicDistributor "
                "no contiene una entrega recuperable. "
                f"requested_event={requested_event!r}, "
                f"delivered_event={delivered_event!r}, "
                f"sim_time={ns.sim_time():.3f} ns"
            )

        cycle_time = (
            p["photon_emission_delay"]
            + (0.5 / p["c"]) * 1e9
        )

        if cycle_time <= 0:
            raise RuntimeError(
                f"El tiempo de ciclo no es positivo: {cycle_time}"
            )

        delivery_duration = float(
            self.delivery.sample.delivery_duration
        )

        failed_attempts = max(
            0,
            int(np.rint(delivery_duration / cycle_time))
        )

        num_attempts = failed_attempts + 1
        bell_index = self.delivery.sample.label[1]

        qubit_A = self.A.qmemory.peek(positions=[0])[0]
        qubit_B = self.B.qmemory.peek(positions=[0])[0]
        self.A.qmemory.execute_instruction(INSTR_X,[0])


        yield self.await_program(self.A.qmemory)

        if bell_index == ns.BellIndex.B11:
            self.A.qmemory.execute_instruction(INSTR_Z,[0])
            yield self.await_program(self.A.qmemory)

        print(qapi.reduced_dm([qubit_A, qubit_B]))

        print(f'Bell state: {self.delivery.sample.label}')
        print(f'Entanglement time: {self.delivery.sample.delivery_duration:.2f} ns')
        print(f'Number of attempts: {num_attempts}')

        self.send_signal("Pair ready")




            